config/routes.rb
Rails.application.routes.draw do
  resources :currencies, only: [:index, :show] do
    collection do
      get :capture
      get :chart_data
    end
  end

  root 'currencies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :prices

  validates :code, uniqueness: true

  def latest_price
    prices.last&.last
  end

  def previous_price
    prices.last&.prev_close
  end
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :currency

  validates :volume_24h, :volume, :transition_time, :status, :session, :prev_close, :last, :current_time, :bid, :ask, presence: true
  validates :volume_24h, :volume, :session, :prev_close, :last, :bid, :ask, numericality: true 

  class << self
    def capture!
      prices = []
      currencies = Array Currency.select(:id, :code)

      # Atomic. All or none

      transaction do
        currencies.each do |currency|
          endpoint = URI "https://data.exchange.coinjar.com/products/#{currency.code}/ticker"

          begin
            response = Net::HTTP.get_response(endpoint)
          rescue SocketError
            return false
          end
          
          return unless response.is_a? Net::HTTPSuccess

          json = JSON.parse(response.body)

          price = currency.prices.new
          price_db_structure = Price.columns_hash

          json.keys.each do |attribute|
            begin
              case price_db_structure[attribute].type
              when :decimal
                json[attribute] = BigDecimal json[attribute]
              when :datetime
                json[attribute] = Time.zone.parse json[attribute] 
              else
                json[attribute] = json[attribute]
              end
            rescue TypeError, ArgumentError => e
              Rails.logger.error "API::DataError, #{e.message}"
              return false
            rescue Exception => e
              Rails.logger.error "API::Outdated, #{e.message}"
              return false
            end
          end

          price.assign_attributes(json)
          prices << price
        end

        return false unless (prices.compact.count == currencies.count && prices.all?(&:valid?))
        prices.each(&:save)
      end

      true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @currencies = Currency.includes(:prices)
  end

  def show
    @currency = Currency.find_by(id: params[:id])
    @prices = @currency ? @currency.prices.order(created_at: :desc).paginate(page: params[:page], per_page: 5) : []
  end

  def capture
    if Price.capture!
      redirect_to root_path, notice: t('currencies.captured')
    else
      redirect_to root_path, flash: { error: t('currencies.capture_error') }
    end
  end

  def chart_data
    currency = Currency.find_by(id: params[:id])
    
    render json: currency.prices.group(:current_time).maximum(:last)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/index.html.erb
<%= button_to t('currencies.capture'), capture_currencies_path, method: :get, class: 'btn btn-primary float-right m-2' %>
<table class='table table-striped table-bordered table-hover'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'><%= t('currencies.name') %></th>
      <th scope='col'><%= t('currencies.code') %></th>
      <th scope='col'><%= t('currencies.latest_price') %></th>
      <th scope='col'><%= t('currencies.previous_price') %></th>
      <th scope='col'><%= t('currencies.actions') %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
	<td scope='col'><%= currency.name %></td>
	<td scope='col'><%= currency.code %></td>
	<td scope='col'><%= currency.latest_price %></td>
	<td scope='col'><%= currency.previous_price %></td>
	<td scope='col'><%= link_to t('currencies.history'), currency %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/currencies/show.html.erb
<div class='clearfix'>
  <%= line_chart chart_data_currencies_path(id: @currency.id), min: @prices.minimum(:last), max: @prices.maximum(:last), xtitle: t('currencies.time'), ytitle: t('currencies.price') %>
</div>

<br />

<table class='table table-striped table-bordered table-hover'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'><%= t('currencies.volume_24h') %></th>
      <th scope='col'><%= t('currencies.volume') %></th>
      <th scope='col'><%= t('currencies.prev_close') %></th>
      <th scope='col'><%= t('currencies.last') %></th>
      <th scope='col'><%= t('currencies.bid') %></th>
      <th scope='col'><%= t('currencies.ask') %></th>
      <th scope='col'><%= t('currencies.current_time') %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @prices.each do |price| %>
      <tr>
	<td scope='col'><%= price.volume_24h %></td>
	<td scope='col'><%= price.volume %></td>
	<td scope='col'><%= price.prev_close %></td>
	<td scope='col'><%= price.last %></td>
	<td scope='col'><%= price.bid %></td>
	<td scope='col'><%= price.ask %></td>
	<td scope='col'><%= price.current_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='digg_pagination'>
  <%= will_paginate @prices, container: false %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piggybank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <div class='d-flex'>
	<%= image_tag 'piggybank', class: 'img-rounded', size: '200x150' %>
	<h1 class='company-name'><%= t('currencies.welcome') %></h1>
      </div>
      <br />

      <% flash.each do |type, msg| %>
        <% alert_class = type == 'notice' ? 'alert-success' : 'alert-danger' %> 
      
        <div class="alert <%= alert_class %>" role='alert'>
	  <%= msg %>
	</div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>